CXXFLAGS += -g -Wall -O3 --std=c++11

OBJS = calculateDiversity calculateDxy calculatePolymorphism listPolyDivSites nonOverlappingWindows

all: $(OBJS)

#test: $(OBJS)
#	./test_scripts.sh

clean:
	rm $(OBJS)
